# Azure Pipeline YAML file

name: 1.6.37$(Rev:.r)

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'

variables:
  _IS_BUILD_CANARY: false
  _RELEASE_NAME: libpng
  _RELEASE_VERSION: v0
  _RELEASE_CONFIGURATION: Release
  _BUILD_VERSION: $(Build.BuildNumber)
  _BUILD_BRANCH: $(Build.SourceBranch)
  # Libpng features to be built
  _LIBPNG_TRIPLETNAME: x86-windows-static

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
- task: PowerShell@2
  displayName: 'Build and Package $(_RELEASE_NAME)'
  inputs:
    filePath: .ci\build.ps1
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: 'Delete $(_RELEASE_NAME) Release (Canary)'
  continueOnError: true
  inputs:
    gitHubConnection: github_ci
    action: delete
    tagSource: manual
    tag: canary
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: 'Create $(_RELEASE_NAME) Release (Canary)'
  inputs:
    gitHubConnection: github_ci
    assets: .dist\*.zip
    isPreRelease: true
    tagSource: manual
    tag: canary
    title: $(_RELEASE_NAME)-$(_RELEASE_VERSION)
    releaseNotesSource: input
    releaseNotes: |
      This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'false'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: 'Create $(_RELEASE_NAME) Release (Stable)'
  inputs:
    gitHubConnection: github_ci
    assets: .dist\*.zip
    title: $(_RELEASE_NAME)-$(_RELEASE_VERSION)
